name: InsynDuelBot
provides: [PracticePlugin, InsynPracticeBotMC]
version: '${version}'
main: dev.insanmiy.practiceplugin.PracticePlugin
api-version: '${minecraftVersion}'
author: insanmiy
description: PvP duels against a custom bot.
commands:
  practice:
    description: PvP bot practice
    aliases: [p, prac]
    usage: /practice <menu|settings|start|stop|pause|resume|rematch|hud|damage|stats|kits|difficulties|kit [editor|info|create|import|edit|save|copy|rename|delete]|status|arena|reload>
    permission: practice.use
permissions:
  practice.use:
    default: true
  practice.admin:
    default: op
  practice.kits:
    description: Create custom kits (up to 50) and edit your own kits
    default: true

